name: Test App

on:
  pull_request:
    branches: main

defaults:
  run:
    working-directory: .

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: oven-sh/setup-bun@v2
      - name: checkout
        uses: actions/checkout@v4
      - name: install
        run: bun install
      - name: format check
        run: bun format:check
      - name: lint check
        run: bun lint:check
